[CmdletBinding()]
param(
    [string] $UpstreamRoot = "",
    [string] $SourceUrl = "https://github.com/BigCiba/vscode-dota2-tools.git",
    [string] $Ref = "main"
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$skillRoot = Resolve-Path -LiteralPath (Join-Path $scriptRoot "..")
$vendorRoot = Join-Path $skillRoot "references\vendor\vscode-dota2-tools"
$tempRoot = $null

if ([string]::IsNullOrWhiteSpace($UpstreamRoot)) {
    $tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("vscode-dota2-tools-" + [System.Guid]::NewGuid().ToString("N"))
    git clone --depth 1 --branch $Ref $SourceUrl $tempRoot | Write-Host
    $UpstreamRoot = $tempRoot
}

$upstreamFullPath = (Resolve-Path -LiteralPath $UpstreamRoot).Path
New-Item -ItemType Directory -Force -Path $vendorRoot | Out-Null

$files = @(
    "resource/dota_script_help2.json",
    "resource/cl_panorama_script_help_2.json",
    "resource/dump_panorama_css_properties.json",
    "resource/dump_panorama_events.md",
    "resource/PanelList.json",
    "resource/PanelList.md",
    "resource/lua_api_changelog.md",
    "css.css-data.json",
    "html.html-data.json"
)

$copied = @()
foreach ($relative in $files) {
    $source = Join-Path $upstreamFullPath ($relative -replace "/", [System.IO.Path]::DirectorySeparatorChar)
    if (!(Test-Path -LiteralPath $source)) {
        Write-Warning "Missing upstream reference: $relative"
        continue
    }

    $destination = Join-Path $vendorRoot ($relative -replace "/", [System.IO.Path]::DirectorySeparatorChar)
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Force
    $copied += $relative
}

$commit = ""
try {
    $commit = (git -C $upstreamFullPath rev-parse HEAD).Trim()
} catch {
    $commit = ""
}

$manifest = [ordered]@{
    source = "BigCiba/vscode-dota2-tools"
    sourceUrl = $SourceUrl
    ref = $Ref
    commit = $commit
    updatedAt = (Get-Date).ToUniversalTime().ToString("o")
    copiedFiles = $copied
    note = "Generated by scripts/update_references.ps1. Do not manually edit vendor snapshots."
}

$manifestPath = Join-Path $vendorRoot "UPSTREAM.json"
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

if ($tempRoot -and (Test-Path -LiteralPath $tempRoot)) {
    Remove-Item -LiteralPath $tempRoot -Recurse -Force
}

Write-Host "Updated DOTA2 references from $SourceUrl at $commit"
Write-Host "Vendor root: $vendorRoot"
